sonar.projectKey=sahty_sym
sonar.projectName=sahty_sym
sonar.projectVersion=1.0

sonar.host.url=http://localhost:9000
sonar.token=PUT_YOUR_SONAR_TOKEN_HERE

sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=tests

sonar.exclusions=vendor/**,var/**,public/**,migrations/**,node_modules/**
sonar.test.inclusions=tests/**
