framework:
    mailer:
        # Transports disponibles
        transports:
            # Transport SMTP Gmail pour envoi réel
            main: '%env(MAILER_DSN)%'
        
        # Options par défaut
        envelope:
            sender: 'maramouerghi1234@gmail.com'
